services:
  - type: web
    name: noan
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PATH
        value: /opt/render/project/python/venv/bin:${PATH}